import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service

s = Service('C:/Chromedriver/chromedriver.exe')
driver = webdriver.Chrome(service=s)
driver.maximize_window()
driver.get('https://qa.neapro.site/login')
#driver.find_element(By.CSS_SELECTOR,".fieldset:nth-child(1) input").click()
driver.find_element(By.CSS_SELECTOR,".fieldset:nth-child(1) input").send_keys("sav105@yandex.ru")
#driver.find_element(By.CSS_SELECTOR,".fieldset:nth-child(2) input").click()
driver.find_element(By.CSS_SELECTOR,".fieldset:nth-child(2) input").send_keys("123456789")
driver.find_element(By.CSS_SELECTOR,".btn").click()
time.sleep(5)
#driver.find_element(By.CSS_SELECTOR,".active .document-tile:nth-child(1)").click()
driver.find_element(By.XPATH,"//*[@id='__layout']/div/div[3]/div/div/div[3]/div/div/div[2]/div[2]/div[1]").click()
time.sleep(5)
driver.find_element(By.CSS_SELECTOR, ".popup_banner_close").click()
driver.find_element(By.ID, "surname").clear()
driver.find_element(By.ID, "surname").send_keys("Ананаска")
driver.find_element(By.ID, "name").clear()
driver.find_element(By.ID, "name").send_keys("Панк")
driver.find_element(By.ID, "patronymic").clear()
driver.find_element(By.ID, "patronymic").send_keys("Ович")
#driver.find_element(By.NAME, "date").click()
driver.find_element(By.NAME, "date").clear()
driver.find_element(By.NAME, "date").send_keys("02.11.2000")
driver.find_element(By.ID, "passportSeries").click()
driver.find_element(By.ID, "passportSeries").clear()
driver.find_element(By.ID, "passportSeries").send_keys("11-11")
#driver.find_element(By.ID, "passportNumber").click()
driver.find_element(By.ID, "passportNumber").clear()
driver.find_element(By.ID, "passportNumber").send_keys("222222")
#driver.find_element(By.CSS_SELECTOR, "#dateOfIssue .mx-input").click()
driver.find_element(By.CSS_SELECTOR, "#dateOfIssue .mx-input").clear()
driver.find_element(By.CSS_SELECTOR, "#dateOfIssue .mx-input").send_keys("10.08.2015")
driver.find_element(By.ID, "code").click()
driver.find_element(By.ID, "code").clear()
driver.find_element(By.ID, "code").send_keys("333-333")
#driver.find_element(By.ID, "cardId").click()
driver.find_element(By.ID, "cardId").clear()
driver.find_element(By.ID, "cardId").send_keys("444-444-444 44")
#driver.find_element(By.ID, "issued").click()
driver.find_element(By.ID, "issued").clear()
driver.find_element(By.ID, "issued").send_keys("пробка-09")
#driver.find_element(By.CSS_SELECTOR, ".vue-dadata__input").click()
driver.find_element(By.CSS_SELECTOR, ".vue-dadata__input").clear()
driver.find_element(By.CSS_SELECTOR, ".vue-dadata__input").send_keys("г Рязань")
time.sleep(3)
driver.find_element(By.CSS_SELECTOR, ".vue-dadata__suggestions-item").click()
#driver.find_element(By.ID, "phone").click()
driver.find_element(By.ID, "phone").clear()
driver.find_element(By.ID, "phone").send_keys("(999)999-99 99")
#driver.find_element(By.CSS_SELECTOR, ".outline").click()
driver.find_element(By.CSS_SELECTOR, ".upload-widget > input").send_keys("D://pasport.jpg")
time.sleep(3)
driver.find_element(By.CSS_SELECTOR, ".fill").click()